### ISSUE TITLE
Mexican Spanish Translation

### ISSUE THREAD

**Issue by ghost** [zer0Kerbal/TheGoldStandard#68] opened 2022-01-25 20:20 UTC
Made one of these.

**Comment by JamesErvin-5** [comment] 2022-01-25 20:20
[Here's the links.](https://github.com/zer0Kerbal/TheGoldStandard/pull/67)

**Comment by zer0Kerbal** [comment] 2022-01-27 06:07
duplicate of #43 . :D

**Closed** 2023-06-07 17:10 UTC
Labels: duplicate
